#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/env.sh"
# The upstream CMake install omits the version file generated by its Rez build.
python - <<'PY'
import configparser
import os
from pathlib import Path
root = Path(os.environ['MOONRAY_LOCAL_ROOT'])
config = configparser.ConfigParser()
config.read(Path(os.environ['MOONRAY_SOURCE_ROOT']) / 'moonray/render_profile_viewer/setup.cfg')
version = config['metadata']['version']
target = root / 'install/python/render_profile_viewer/render_profile_viewer/_version.py'
target.write_text('__version__ = ' + repr(version) + '\n')
PY
python -m pip install --no-index --no-deps --no-build-isolation --prefix "$DEPS_ROOT" \
  "$MOONRAY_LOCAL_ROOT/install/python/render_profile_viewer"
