"""Native RDL scene export for complete MoonRay object/reference graphs."""
from __future__ import annotations

from collections import defaultdict
import math
from pathlib import Path

from .model import GraphError, LIGHT_SAMPLING, LOBE_SAMPLES, MATRIX_TYPES, RAY_DEPTHS, SHADER_TYPES, VECTOR_TYPES
from .shader_adapters import native_graph


def quote(value):
    # Lua decimal escapes avoid JSON's unsupported \uXXXX escapes.
    return '"' + ''.join('\\' + c if c in '\\"' else f'\\{ord(c):03d}' if ord(c) < 32 else c for c in str(value)) + '"'


def value(kind, data):
    if kind.endswith("Vector"):
        return "{" + ", ".join(value(kind[:-6], item) for item in data) + "}"
    if kind in MATRIX_TYPES:
        return f"Mat{MATRIX_TYPES[kind]}(" + ", ".join(repr(float(x)) for row in data for x in row) + ")"
    if kind in VECTOR_TYPES:
        constructor = kind if kind in {"Rgb", "Rgba"} else "Vec" + str(VECTOR_TYPES[kind])
        return constructor + "(" + ", ".join(repr(float(x)) for x in data) + ")"
    if kind == "String":
        return quote(data)
    if kind == "Bool":
        return "true" if data else "false"
    return repr(data)


class Writer:
    def __init__(self):
        self.lines = ["-- Generated by Lunatic.\n"]

    def declare(self, name, kind, path):
        self.lines.append(f"{name} = {kind}({quote(path)})")
        return name

    def set(self, name, properties):
        self.lines.append(name + " {\n" + "\n".join(f"    [{quote(key)}] = {expression}," for key, expression in properties.items()) + "\n}")

    def members(self, name, members):
        self.lines.append(name + " { " + ", ".join(members) + " }")


def preview_geometry(graph):
    selected = graph.data["preview"]["geometry"]
    if selected != "auto":
        return selected
    if graph.data["volume"]:
        return "vdb" if graph.node(graph.data["volume"])["shader"] == "VdbVolume" else "volume"
    if graph.data["surface"] and graph.catalog.definition(graph.node(graph.data["surface"])["shader"])["type"] == "DwaBaseHairLayerable":
        return "hair"
    return "light_rig" if graph.data["light"] else "sphere"


def mesh_data(preset, settings):
    if preset in {"sphere", "light_rig"}:
        from pxr import Usd
        from .worker import create_preview_sphere
        from pxr import UsdShade, UsdGeom
        stage = Usd.Stage.CreateInMemory()
        material = UsdShade.Material.Define(stage, "/Material")
        mesh = create_preview_sphere(stage, material, settings)
        return ([list(p) for p in mesh.GetPointsAttr().Get()], list(mesh.GetFaceVertexCountsAttr().Get()),
                list(mesh.GetFaceVertexIndicesAttr().Get()), [list(p) for p in UsdGeom.PrimvarsAPI(mesh).GetPrimvar("st").Get()])
    if preset in {"cube", "volume"}:
        points = [[x, y, z] for z in (-0.8, 0.8) for y in (-0.8, 0.8) for x in (-0.8, 0.8)]
        indices = [0, 2, 3, 1, 4, 5, 7, 6, 0, 4, 6, 2, 1, 3, 7, 5, 2, 6, 7, 3, 0, 1, 5, 4]
        return points, [4] * 6, indices, [[0, 0], [1, 0], [1, 1], [0, 1]] * 6
    steps = 32 if preset == "cloth" else 1
    points, counts, indices, uv = [], [], [], []
    for j in range(steps + 1):
        for i in range(steps + 1):
            x, y = 2 * i / steps - 1, 2 * j / steps - 1
            z = 0.15 * math.sin(x * 7) * math.cos(y * 3) if preset == "cloth" else 0
            points.append([x, y, z])
    for j in range(steps):
        for i in range(steps):
            a = j * (steps + 1) + i
            counts.append(4)
            indices += [a, a + 1, a + steps + 2, a + steps + 1]
            uv += [[i / steps, j / steps], [(i + 1) / steps, j / steps], [(i + 1) / steps, (j + 1) / steps], [i / steps, (j + 1) / steps]]
    return points, counts, indices, uv


def create_geometry(writer, graph):
    settings = graph.data["preview"]
    preset = preview_geometry(graph)
    if preset == "hair":
        writer.declare("preview_object", "RdlCurveGeometry", "/Preview/Object")
        points, radii, uv = [], [], []
        for strand in range(180):
            u = (strand % 30) / 29
            depth = (strand // 30) / 5
            for j in range(8):
                t = j / 7
                points.append([(u - 0.5) * 1.6 + 0.10 * math.sin(t * 4 + u * 2), -1 + t * 2, (depth - .5) * .65 + 0.18 * math.sin(t * 3 + u * 5)])
                radii.append(.008 * (1 - .7 * t))
            uv.append([u, depth])
        writer.set("preview_object", {"curve_type": "2", "curves_subtype": "1", "tessellation_rate": "8",
                   "curves_vertex_count": value("IntVector", [8] * 180), "vertex_list_0": value("Vec3fVector", points),
                   "radius_list": value("FloatVector", radii), "uv_list": value("Vec2fVector", uv)})
    elif preset == "vdb":
        path = Path(settings["vdb_file"]).expanduser()
        if not settings["vdb_file"] or not path.is_file():
            raise GraphError("Choose an existing VDB file in Preview setup for the VDB preview")
        writer.declare("preview_object", "VdbGeometry", "/Preview/Object")
        writer.set("preview_object", {"model": quote(path.resolve()), "density_grid": quote(settings["vdb_grid"]), "node_xform": value("Mat4d", [[settings["vdb_scale"],0,0,0], [0,settings["vdb_scale"],0,0], [0,0,settings["vdb_scale"],0], [*settings["vdb_offset"],1]])})
    else:
        points, counts, indices, uv = mesh_data(preset, settings)
        writer.declare("preview_object", "RdlMeshGeometry", "/Preview/Object")
        writer.set("preview_object", {"vertex_list_0": value("Vec3fVector", points), "face_vertex_count": value("IntVector", counts),
                   "vertices_by_index": value("IntVector", indices), "uv_list": value("Vec2fVector", uv),
                   "is_subd": "true" if settings["subdivision_scheme"] != "none" else "false",
                   "subd_scheme": "0" if settings["subdivision_scheme"] == "bilinear" else "1",
                   "mesh_resolution": str(settings["mesh_resolution"]), "adaptive_error": str(settings["adaptive_error"]),
                   "smooth_normal": "true" if preset in {"sphere", "cloth", "light_rig"} else "false"})
    return preset


def create_scene(graph, path, output_dir, size=512):
    """Create a complete native scene. Output images are constrained to output_dir."""
    from pxr import Gf
    graph.validate(require_surface=True)
    from .tx_cache import prepared_graph
    from .light_graph import prepare_light_maps
    graph = prepare_light_maps(graph, Path(output_dir) / "light-textures")
    graph = prepared_graph(graph)
    graph = native_graph(graph)
    writer = Writer()
    names = graph.export_names()
    material_namespace = "/Graph/" + graph.material_export_name() + "/"
    writer.lines.append("material_name = " + quote(graph.data["name"]))
    settings = graph.data["preview"]
    out = Path(output_dir).resolve()
    writer.declare("preview_camera", "PerspectiveCamera", "/Preview/Camera")
    from .preview_camera import default_values
    camera = default_values()
    writer.set("preview_camera", {"node_xform": value("Mat4d", camera["node_xform"]), "focal": "50", "film_width_aperture": "30"})
    custom_geometry = (settings["geometry"] == "auto" and graph.data["geometry"]
                       and graph.node(graph.data["geometry"])["shader"] != "PreviewObject")
    preset = "custom" if custom_geometry else create_geometry(writer, graph)
    writer.declare("preview_ground", "RdlMeshGeometry", "/Preview/Ground")
    writer.set("preview_ground", {"vertex_list_0": value("Vec3fVector", [[-200, -1.02, -200], [-200, -1.02, 200], [200, -1.02, 200], [200, -1.02, -200]]),
               "face_vertex_count": "{4}", "vertices_by_index": "{0,1,2,3}", "is_subd": "false"})
    writer.declare("floor_material", "DwaBaseMaterial", "/Preview/Floor")
    writer.set("floor_material", {"albedo": "Rgb(.085,.1,.12)", "roughness": "0.7"})
    writer.declare("fallback_material", "DwaBaseMaterial", "/Preview/DefaultMaterial")
    writer.set("fallback_material", {"albedo": "Rgb(.5,.5,.5)", "roughness": ".4"})
    for name, pos, intensity, color, width in [
        ("key", (-3, 4, 3), 6, (1, .92, .83), 3), ("fill", (3, 1, 2), 2, (.75, .85, 1), 2.5), ("rim", (.5, 3, -2), 7.5, (.85, .95, 1), 2)]:
        writer.declare("preview_" + name, "RectLight", "/Preview/" + name)
        matrix = Gf.Matrix4d().SetLookAt(Gf.Vec3d(*pos), Gf.Vec3d(0), Gf.Vec3d(0, 1, 0)).GetInverse()
        writer.set("preview_" + name, {"node_xform": value("Mat4d", [list(row) for row in matrix]), "intensity": str(intensity),
                   "color": value("Rgb", [c * settings["studio_light_level"] for c in color]), "width": str(width), "height": str(width), "normalized": "false"})
    writer.declare("preview_ambient", "EnvLight", "/Preview/Ambient")
    # Keep positive intensities with black colors at level zero so USD copies
    # also suppress hdMoonray's automatic fallback environment light.
    writer.set("preview_ambient", {"intensity": ".12", "color": value("Rgb", [c * settings["studio_light_level"] for c in (.65, .73, .85)])})
    refs = {"PreviewObject": "preview_object", "PreviewCamera": "preview_camera", "PreviewKeyLight": "preview_key"}
    expressions = {}
    for index, node in enumerate(graph.data["nodes"]):
        if node["shader"] in refs:
            expressions[node["id"]] = refs[node["shader"]]
        else:
            expressions[node["id"]] = writer.declare("graph_node_" + str(index), node["shader"], material_namespace + names[node["id"]])

    object_ref = expressions[graph.data["geometry"]] if custom_geometry else "preview_object"
    camera_ref = expressions.get(graph.data["camera"], "preview_camera")
    for node in graph.data["nodes"]:
        if node["shader"] == "PreviewObject":
            expressions[node["id"]] = object_ref
        elif node["shader"] == "PreviewCamera":
            expressions[node["id"]] = camera_ref

    # Reference nodes alias existing scene objects, but retain their user-given names.
    writer.lines.append("graph_references = {}")
    for node in graph.data["nodes"]:
        if node["shader"] in refs:
            reference = "graph_references[" + quote(names[node["id"]]) + "]"
            writer.lines.append(reference + " = " + expressions[node["id"]])
            expressions[node["id"]] = reference

    # Channel adapters make the same output socket behavior work for all native maps.
    channels = {}
    for connection in graph.data["connections"]:
        node_id, channel = connection["source"], connection.get("output", "out")
        if channel == "out" or (node_id, channel) in channels:
            continue
        node = graph.node(node_id)
        name = "graph_channel_" + str(len(channels))
        if channel == "a":
            writer.declare(name, node["shader"], "/Channels/" + name)
            channels[node_id, channel] = name
        else:
            writer.declare(name, "RgbToFloatMap", "/Channels/" + name)
            writer.set(name, {"input": "bind(" + expressions[node_id] + ")", "mode": str({"r": 0, "g": 1, "b": 2}[channel])})
            channels[node_id, channel] = name
    grouped = defaultdict(list)
    for connection in graph.data["connections"]:
        grouped[connection["target"], connection["input"]].append(connection)

    for node in graph.data["nodes"]:
        if node["shader"] in refs:
            continue
        attrs = graph.catalog.attributes(node["shader"])
        properties = {name: value(attrs[name]["attrType"], v) for name, v in node["values"].items()}
        for name, attr in attrs.items():
            incoming = grouped.get((node["id"], name), [])
            if not incoming:
                continue
            sources = [channels.get((c["source"], c.get("output", "out")), expressions[c["source"]]) for c in incoming]
            t = attr["attrType"]
            properties[name] = ("{" + ", ".join(sources) + "}" if t in {"SceneObjectVector", "SceneObjectIndexable"} else
                                sources[0] if t == "SceneObject*" else "bind(" + sources[0] + ", " + value(t, graph.value(node, name)) + ")")
        kind = graph.catalog.definition(node["shader"])["type"]
        if kind == "RenderOutput":
            properties.update(file_name=quote(out / ("aov_" + names[node["id"]] + ".exr")), active="true")
            # Keep diagnostic channels unambiguous in the per-node image.
            properties.update(channel_name=quote(""), file_part=quote(""))
        if kind == "Metadata":
            columns = [graph.value(node, key) for key in ("name", "type", "value")]
            if len({len(column) for column in columns}) != 1:
                raise GraphError("Metadata name, type and value lists must have matching lengths.")
            writer.members(expressions[node["id"]], ["{" + ", ".join(quote(part) for part in row) + "}"
                                                       for row in zip(*columns)])
        elif kind in {"LightSet", "LightFilterSet", "GeometrySet", "ShadowSet", "ShadowReceiverSet", "TraceSet"}:
            members = [expressions[c["source"]] for c in graph.data["connections"] if c["target"] == node["id"]]
            if kind == "TraceSet":
                parts = node["values"].get("parts", [])
                members = ["{" + member + ", " + quote(parts[i] if i < len(parts) else "") + "}" for i, member in enumerate(members)]
            writer.members(expressions[node["id"]], members)
            if kind == "ShadowReceiverSet" and "complement" in properties:
                writer.lines.append(expressions[node["id"]] + '["complement"] = ' + properties["complement"])
        else:
            writer.set(expressions[node["id"]], properties)
            if (node["id"], "a") in channels:
                alpha_properties = dict(properties)
                alpha_properties["alpha_only" if node["shader"] == "ImageMap" else "output_mode"] = "true" if node["shader"] == "ImageMap" else "4"
                writer.set(channels[node["id"], "a"], alpha_properties)

    writer.declare("preview_lights", "LightSet", "/Preview/Lights")
    writer.members("preview_lights", [expressions[graph.data["light"]]] if graph.data["light"] else ["preview_key", "preview_fill", "preview_rim", "preview_ambient"])
    writer.declare("preview_geometry", "GeometrySet", "/Preview/Geometry")
    writer.members("preview_geometry", [object_ref, "preview_ground"])
    writer.declare("preview_layer", "Layer", "/Preview/Layer")
    surface = expressions.get(graph.data["surface"], "fallback_material")
    volume = expressions.get(graph.data["volume"])
    displacement = expressions.get(graph.data["displacement"]) if settings["displacement_enabled"] else None
    lightset = expressions.get(graph.data["lightset"], "preview_lights")
    assignment = [object_ref, quote(""), lightset]
    if preset not in {"volume", "vdb"} and (graph.data["surface"] or not volume):
        assignment.append(surface)
    if volume:
        assignment.append(volume)
    if displacement and preset not in {"hair", "volume", "vdb"}:
        assignment.append(displacement)
    writer.members("preview_layer", ["{" + ", ".join(assignment) + "}", '{preview_ground, "", floor_material, ' + lightset + '}'])
    writer.set("SceneVariables", {"camera": camera_ref, "layer": "preview_layer", "image_width": str(size), "image_height": str(size),
               "pixel_samples": str(settings["samples"]), "pixel_filter_width": "2",
               **{key: str(settings[key]) for key in (*RAY_DEPTHS, *LOBE_SAMPLES, *LIGHT_SAMPLING)},
               "enable_displacement": "true" if settings["displacement_enabled"] else "false",
               "shadow_terminator_fix": str(settings["shadow_terminator_fix"]),
               "output_file": quote(out / "beauty.exr"), "enable_motion_blur": "false"})
    selected_path = out / "beauty.exr"
    if graph.data["display"]:
        writer.declare("selected_output", "RenderOutput", "/Preview/SelectedOutput")
        selected_path = out / "selected.exr"
        writer.set("selected_output", {"result": "15", "display_filter": expressions[graph.data["display"]], "file_name": quote(selected_path)})
    elif graph.data["aov"]:
        selected_path = out / ("aov_" + names[graph.data["aov"]] + ".exr")
    elif settings["render_view"] != "beauty":
        writer.declare("selected_output", "RenderOutput", "/Preview/SelectedOutput")
        selected_path = out / "selected.exr"
        view = settings["render_view"]
        props = {"file_name": quote(selected_path)}
        if view in {"albedo", "roughness"}:
            props.update(result="7", material_aov=quote(view))
        elif view in {"normal", "uv"}:
            props.update(result="3", state_variable="2" if view == "normal" else "3")
        else:
            props["result"] = "2" if view == "depth" else "6"
        writer.set("selected_output", props)
    Path(path).write_text("\n\n".join(writer.lines) + "\n")
    return selected_path
